import {DAYS,COLORS,DEFAULT_SLOTS,uid,course,emptySchedule,validateSchedule,parseWeeks,formatWeeks,today,weekOf,addDays,onDate,events,conflicts,parseCSV,exportCSV,exportICS} from './core.js';
import {readPDF} from './pdf.js';
import {readSheet as readXlsxFile} from 'read-excel-file/browser';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const native=globalThis.KeyuNative;
let state={version:1,active:'',schedules:[],theme:'auto'},view='week',week=1,pending=null,focusBefore=null;
try{const saved=native?.getState?.()||localStorage.getItem('keyu-v1');if(saved){const x=JSON.parse(saved);if(x.version!==1||!Array.isArray(x.schedules))throw Error('备份版本不受支持');state={...state,...x,schedules:x.schedules.map(validateSchedule)};}}catch(e){setTimeout(()=>toast('保存的课表读取失败，请通过 JSON 备份恢复：'+e.message),200);}
if(!state.schedules.length){const s=emptySchedule();state.schedules=[s];state.active=s.id;}
if(!state.schedules.some(s=>s.id===state.active))state.active=state.schedules[0].id;
const current=()=>state.schedules.find(s=>s.id===state.active);
const clampWeek=w=>Math.max(1,Math.min(current().totalWeeks,w));week=clampWeek(weekOf(current(),today()));
function persist(){const data=JSON.stringify(state);if(native)native.saveState(data);else localStorage.setItem('keyu-v1',data);syncNative();}
function commit(next){const previous=state;state=next;try{persist();}catch(e){state=previous;throw Error('保存失败，原课表保留。请检查设备存储空间。');}render();}
function saveSchedule(s){s=validateSchedule(s);commit({...state,schedules:state.schedules.map(x=>x.id===s.id?s:x)});}
function syncNative(){if(!native)return;const s=current();const ev=s.startDate?events(s).map(e=>({at:Date.parse(`${e.date}T${e.from}:00+08:00`)-s.reminder*60000,end:Date.parse(`${e.date}T${e.to}:00+08:00`),title:e.name,body:`${e.from} · ${e.room||'地点待定'} · ${e.teacher}`})):[];native.syncEvents(JSON.stringify(ev));}
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',6500);}
function modal(title,body){focusBefore=document.activeElement;$('#modal').innerHTML=`<section class="dialog" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="dialog-head"><h2>${esc(title)}</h2><button data-action="close" aria-label="关闭">×</button></div>${body}<p class="error" id="form-error" role="alert"></p></section>`;$('#modal').hidden=false;$('#app').inert=true;$('#modal').querySelector('input,button')?.focus();}
function close(){if($('#modal').hidden)return;$('#modal').hidden=true;$('#app').inert=false;focusBefore?.focus();}
function field(label,name,value='',type='text',extra=''){return `<label class="field">${label}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function select(label,name,options,value){return `<label class="field">${label}<select name="${name}">${options.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;}
function nextEvent(s){if(!s.startDate)return null;return events(s).find(e=>Date.parse(`${e.date}T${e.to}:00+08:00`)>Date.now());}
function render(){
 const s=current();document.body.className='theme-'+state.theme;
 const nav=[['week','▦','每周课表'],['list','☷','全部课程'],['import','↥','导入课表'],['settings','⚙','课表设置'],['help','ⓘ','使用帮助']];
 const names={week:s.name,list:'全部课程',import:'导入你的课表',settings:'课表设置',help:'让每台手机都能看课表'};
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><img src="icon.svg" alt=""><div>课屿<small>KEYU TIMETABLE</small></div></div><nav class="nav" aria-label="主导航">${nav.map(([id,icon,label])=>`<button data-view="${id}" class="${view===id?'active':''}"><span class="nav-icon">${icon}</span>${label}</button>`).join('')}</nav><div class="side-bottom"><div class="local-badge"><i class="dot"></i>课表只保存在这台设备</div>课屿 1.0.0 · 开源免费<br>留一点时间，给生活。</div></aside><main class="main"><header class="topbar"><div><div class="eyebrow">KEYU / YOUR TIME, YOUR PACE</div><h1>${esc(names[view])}</h1><div class="muted subtitle">${view==='week'?(s.startDate?`第 1 周 · ${s.startDate} 起`:'从导入一份课表开始'):'离线可用 · 无账号 · 无广告'}</div></div><div class="actions"><button class="desktop" data-action="export">↗ 导出</button><button class="primary" data-action="add">＋ 添加课程</button></div></header>${state.schedules.length>1?`<label class="field" style="max-width:300px">切换课表<select id="schedule-switch">${state.schedules.map(x=>`<option value="${esc(x.id)}" ${x.id===s.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`:''}${view==='week'?weekView(s):view==='list'?listView(s):view==='import'?importView():view==='settings'?settingsView(s):helpView()}<footer class="page-footer"><span><i class="dot"></i> 本地保存，安心下线</span><span>课屿 / 01 · 把时间留给生活</span></footer></main></div>`;
}
function weekView(s){
 const start=s.startDate?addDays(s.startDate,(week-1)*7):'',shown=[];
 for(let d=1;d<=7;d++){const date=start?addDays(start,d-1):'';for(const c of date?onDate(s,date):s.courses.filter(c=>c.day===d&&c.weeks.includes(week)))shown.push({...c,displayDay:d});}
 let grid='<div class="dayhead">'+(start?`${+start.slice(5,7)}月`:'周次')+'</div>';
 for(let d=1;d<=7;d++){const date=start?addDays(start,d-1):'';grid+=`<div class="dayhead ${date===today()?'today':''}">周${DAYS[d-1]}<strong>${date?+date.slice(8):'—'}</strong></div>`;}
 s.slots.forEach((slot,i)=>{grid+=`<div class="slot" style="grid-row:${i+2};grid-column:1"><b>${i+1}</b><span>${slot.slice(0,5)}</span><span>${slot.slice(6)}</span></div>`;for(let d=1;d<=7;d++)grid+=`<div class="gridcell" style="grid-row:${i+2};grid-column:${d+1}"></div>`;});
 shown.forEach(c=>{const peers=shown.filter(x=>x.displayDay===c.displayDay&&x.start<=c.end&&x.end>=c.start),over=peers.length>1;grid+=`<button class="course-card ${over?'overlap':''}" data-course="${esc(c.id)}" style="--course:${c.color};grid-column:${c.displayDay+1};grid-row:${c.start+1}/span ${c.end-c.start+1};${over?`margin-left:${peers.findIndex(x=>x.id===c.id)*45/peers.length}%;width:${100/peers.length}%;`:''}" title="${esc(c.name+' '+c.room)}"><strong>${esc(c.name)}</strong><span>${esc(c.room||'地点待定')}</span><span class="teacher">${esc(c.teacher)}</span><span>${c.start}–${c.end}节${over?' · 冲突':''}</span></button>`;});
 const next=nextEvent(s),tod=s.startDate?onDate(s,today()):[];
 return `${!s.startDate?'<div class="notice warning">尚未设置第 1 周周一日期，当前只按周次显示。日期提醒暂不可用。<button data-view="settings">设置日期</button></div>':''}${s.notes.length?`<div class="notice">学期事项：${s.notes.map(esc).join('；')}（未指定节次的事项不生成上课提醒）</div>`:''}<div class="layout"><section class="panel schedule-panel"><div class="weekbar"><div><strong>第 ${week} 周</strong> <span class="pill">${week%2?'单周':'双周'}</span><div class="weekdates">${start?`${start} — ${addDays(start,6)}`:'设置日期后显示日历'}</div></div><div class="weekbuttons"><button data-action="prev" aria-label="上一周" ${week<=1?'disabled':''}>‹</button><button data-action="today">本周</button><button data-action="next" aria-label="下一周" ${week>=s.totalWeeks?'disabled':''}>›</button></div></div>${!s.courses.length?`<div class="empty"><div class="symbol">▦</div><h2>新学期，从这里开始</h2><p>导入教务 PDF，课程就有了自己的位置。<br>你的文件只在设备上解析。</p><button class="primary" data-view="import">导入课表</button><button data-action="demo">看看示例</button></div>`:`<div class="table-scroll"><div class="timetable" style="--slots:${s.slots.length}">${grid}</div></div>${!shown.length?'<div class="notice" style="margin:12px">本周没有按节次安排的课程，请同时查看学期事项与学校通知。</div>':''}`}</section><aside class="aside"><section class="panel next"><span class="pill">${next?'下一段学习时光':'留一点空白'}</span><h2>${next?esc(next.name):'今天，也要好好生活。'}</h2><small>${next?`${next.date} · ${next.from}–${next.to}<br>${esc(next.room||'地点待定')}`:'导入课表后，在这里遇见下一节课。'}</small></section><section class="panel summary"><h3>这一周的小计</h3><div class="statrow"><span>课程时段</span><b>${shown.length}<small> 次</small></b></div><div class="statrow"><span>学习节数</span><b>${shown.reduce((n,c)=>n+c.end-c.start+1,0)}<small> 节</small></b></div><div class="statrow"><span>学期进度</span><span>${week} / ${s.totalWeeks} 周</span></div></section><section class="panel today-list"><h3>今天的安排 <span class="muted">/ ${today().slice(5)}</span></h3>${tod.length?tod.map(c=>`<div class="timeline-item"><time>${s.slots[c.start-1].slice(0,5)}</time><div><strong>${esc(c.name)}</strong><br><small>${esc(c.room)}</small></div></div>`).join(''):'<p class="muted">今天暂无按节次安排的课程。</p>'}</section></aside></div>`;
}
function listView(s){return `<section class="panel content-panel"><div class="field"><label for="search">查找课程、教师或教室</label><input id="search" placeholder="输入关键词"></div><div id="course-list">${listItems(s.courses)}</div><div class="button-row"><button data-action="export">导出课表 / 日历</button></div></section>`;}
function listItems(cs){return cs.length?cs.map(c=>`<article class="list-item"><div><strong>${esc(c.name)}</strong><p>周${DAYS[c.day-1]} · ${c.start}–${c.end}节 · 第 ${formatWeeks(c.weeks)} 周</p><small>${esc([c.room,c.teacher].filter(Boolean).join(' · '))}</small></div><button data-course="${esc(c.id)}">编辑</button></article>`).join(''):'<p class="muted">没有匹配的课程。</p>';}
function importView(){return `<section class="panel content-panel"><div class="notice">文件在本机解析，不需要学号、密码，也不会上传课表。导入会新建一张课表，原课表保留。</div><div class="cards"><article class="import-card"><div class="number">01 / 教务导出</div><h3>华工教务 PDF</h3><p>在教务“个人课表查询”中选择“输出 PDF”。支持文字版七列课表、多页、单双周与不同周次的教室变化。</p><button class="primary" data-action="pick" data-accept=".pdf">选择 PDF 文件</button></article><article class="import-card"><div class="number">02 / 通用格式</div><h3>Excel / CSV / 表格 HTML</h3><p>按 WakeUp 七列表头填写：课程名称、星期、开始节数、结束节数、老师、地点、周数。Excel 支持 .xlsx 第一张工作表。</p><button data-action="pick" data-accept=".xlsx,.csv,.html,.htm,.txt">选择表格文件</button><button class="ghost" data-action="template">下载 CSV 模板 ↗</button></article><article class="import-card"><div class="number">03 / 备份迁移</div><h3>课屿 JSON 备份</h3><p>恢复课程、学期日期、时间表和调休。不同手机可通过文件迁移，不依赖云账号。</p><button data-action="pick" data-accept=".json">选择 JSON 文件</button></article><article class="import-card"><div class="number">04 / 手动整理</div><h3>粘贴 CSV 文本</h3><p>也可以先添加课程，再随时修改。截图或未适配的教务 PDF 暂不自动识别，避免误导入。</p><button data-action="paste">粘贴文本</button></article></div><input id="file-input" type="file" hidden><hr class="divider"><h3>从 WakeUp 迁移</h3><p class="muted">目前支持官方七列 CSV 格式；不把 WakeUp 私有备份、分享口令或任意学校文件误当成通用格式。日历导出可在“导出”中找到。</p></section>`;}
function settingsView(s){return `<section class="panel content-panel"><form id="settings-form"><div class="form-grid">${field('课表名称','name',s.name,'text','required maxlength="80"')}${field('第 1 周的周一','startDate',s.startDate,'date')}${field('学期周数','totalWeeks',s.totalWeeks,'number','min="1" max="60" required')}${select('上课前提醒','reminder',[[0,'上课时'],[5,'提前 5 分钟'],[10,'提前 10 分钟'],[15,'提前 15 分钟'],[20,'提前 20 分钟'],[30,'提前 30 分钟'],[60,'提前 1 小时']],s.reminder)}</div><label class="field">每节课的时间（每行一节，24 小时制）<textarea name="slots" rows="7" required>${esc(s.slots.join('\n'))}</textarea><small>默认时间仅为示例，请按校区核对。所有课程日期按中国标准时间 UTC+8 生成。</small></label><label class="field">学期事项（每行一条）<textarea name="notes" rows="3">${esc(s.notes.join('\n'))}</textarea></label><button class="primary" type="submit">保存设置</button><p class="error" id="settings-error" role="alert"></p></form><hr class="divider"><h3>节假日与调课</h3><p class="muted">不自动猜测学校放假安排。指定某天停课，或让某天使用另一日期原本的课程；不会递归跟随另一条调休。</p>${Object.entries(s.adjustments).sort().map(([d,src])=>`<div class="list-item"><span>${esc(d)} → ${src?'按 '+esc(src)+' 的原课程':'停课'}</span><button data-remove-adjust="${esc(d)}">移除</button></div>`).join('')}<button data-action="adjust">＋ 添加停课 / 补课</button><hr class="divider"><h3>外观与提醒</h3>${select('显示主题','theme',[['auto','跟随系统'],['light','浅色'],['dark','深色']],state.theme)}${native?`<div class="notice">${esc(native.getReminderStatus())}</div><div class="button-row"><button data-action="notifications">启用上课提醒</button><button data-action="native-settings">系统通知设置</button><button data-action="disable-notifications">关闭提醒</button></div>`:'<p class="muted">浏览器关闭后无法可靠运行定时提醒。请导出 ICS 到系统日历，或在 Android 上使用 APK 的本地通知。</p>'}<div class="button-row"><button data-action="export">导出备份 / 日历</button><button class="danger" data-action="delete-schedule">删除当前课表</button></div></section>`;}
function helpView(){return `<section class="panel content-panel about-text"><h2>你的课表，应当属于你</h2><p>课屿是一款独立开源课表工具。先导入文件，核对课程，再设置学期和节次时间，即可离线查看。</p><h3>不同手机怎么用</h3><ul><li><b>Android：</b>使用 APK 或浏览器版。APK 的课程提醒使用系统闹钟与通知；要允许通知，准确提醒还需要系统的“闹钟和提醒”权限。省电策略、强行停止应用可能影响提醒。</li><li><b>iPhone / iPad：</b>用 Safari 打开网页版，可通过分享菜单添加到主屏幕。后台提醒使用导出的 ICS 文件，在支持导入的日历客户端中添加。</li><li><b>华为：</b>可安装 Android 应用的系统可试用 APK；原生 HarmonyOS 使用浏览器版。本项目没有把 APK 声称为原生鸿蒙安装包。</li><li><b>微信内置浏览器：</b>如果不能选文件或保存，请用系统浏览器打开。先在教务网页下载 PDF，再手动选文件导入。</li></ul><h3>导入的边界</h3><p>PDF 目前适配华工教务输出的文字版七列表格。CSV、XLSX 和 HTML 使用相同七列表头。扫描件、图片、旧版 XLS、任意排版 Excel、WakeUp 私有备份和教务自动登录暂不支持。导入前会显示每条结果，无时间的实践课程保留为学期事项。</p><h3>备份与更新</h3><p>网页版课表保存在当前浏览器，清理网站数据或卸载可能删除课表。APK 保存在应用私有空间。同一签名和包名的覆盖更新保留数据，卸载不保留。换设备或更新前可导出 JSON。导入文件始终新建课表，不覆盖已有课表。</p><h3>日期和调休</h3><p>输入校历第 1 周周一，而不是首次上课日期。按“停课 / 补课”逐个设置学校通知中的特殊日期。补课只复制源日期原本的课程，源日期如需停课须另加一条停课设置。ICS 是导出时的快照，修改课表后需重新导出；建议导入独立日历以便替换，避免重复。</p><h3>隐私与兼容性</h3><p>无登录、广告或统计 SDK。课表文件仅在设备解析，未发送到服务器。网页版首次加载需要下载程序；浏览器缓存完整后可离线使用，系统清理缓存后需重新联网。公开源码使用虚构示例。手机适配以实测记录为准，尚未完成各品牌真机验收。</p><p><a href="https://github.com/KevinKaslana093/keyu-timetable" target="_blank" rel="noopener">查看开源项目 ↗</a> · <a href="https://github.com/KevinKaslana093/keyu-timetable/releases" target="_blank" rel="noopener">下载 Android APK ↗</a></p></section>`;}
function editCourse(id){const s=current(),c=s.courses.find(x=>x.id===id)||{id:uid(),name:'',day:1,start:1,end:2,weeks:[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16],teacher:'',room:'',note:'',color:COLORS[s.courses.length%COLORS.length]};modal(id?'编辑课程':'添加课程',`<form id="course-form" data-id="${esc(c.id)}"><div class="form-grid">${field('课程名称','name',c.name,'text','required maxlength="120"')}${select('星期','day',DAYS.map((d,i)=>[i+1,'周'+d]),c.day)}${field('开始节数','start',c.start,'number',`min="1" max="${s.slots.length}" required`)}${field('结束节数','end',c.end,'number',`min="1" max="${s.slots.length}" required`)}${field('教师','teacher',c.teacher)}${field('地点','room',c.room)}</div>${field('周数，例如 3-12、15-18 或 3-17单','weeks',formatWeeks(c.weeks),'text','required')}${field('课程颜色','color',c.color,'color')}${field('备注','note',c.note)}<div class="button-row"><button class="primary" type="submit">保存课程</button>${id?`<button type="button" class="danger" data-delete-course="${esc(id)}">删除课程</button>`:''}</div></form>`);}
function download(name,text,mime){if(native){native.saveFile(name,mime,text);return;}const blob=new Blob([text],{type:mime}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function exportDialog(){const s=current();modal('带走你的课表',`<p class="muted">JSON 保留完整设置；CSV 便于编辑；ICS 交给系统日历提醒。</p><div class="button-row"><button data-action="json">JSON 备份</button><button data-action="csv">CSV 课表</button><button class="primary" data-action="ics" ${!s.startDate?'disabled':''}>ICS 系统日历</button></div>${!s.startDate?'<p class="notice warning">导出日历前，请先设置第 1 周周一日期。</p>':''}<p class="muted" style="margin-top:20px">ICS 是快照，重复导入可能重复提醒。课表更新后请替换原来的课程日历。浏览器版不会在后台自行发送上课通知。</p>`);}
function preview(result,filename){
 const s=result.schedule?validateSchedule(result.schedule):{...emptySchedule(),courses:result.courses,notes:result.notes||[]};s.id=uid();s.courses=s.courses.map(c=>({...c,id:uid()}));if(!result.schedule)s.name=filename.replace(/\.[^.]+$/,'')||'新课表';s.totalWeeks=Math.max(s.totalWeeks,...s.courses.flatMap(c=>c.weeks));
 while(s.slots.length<Math.max(...s.courses.map(c=>c.end)))throw Error('课程超过默认 12 节，请先将文件整理为带完整时间表的 JSON');
 pending=s;const warns=conflicts(s);
 modal('核对导入结果',`<div class="preview-info"><span class="pill">${new Set(s.courses.map(c=>c.name)).size} 门课程</span><span class="pill">${s.courses.length} 条时段</span><span class="pill">${s.notes.length} 条学期事项</span></div>${warns.length?`<div class="notice warning">发现时间冲突：${warns.map(esc).join('；')}。导入后请在“全部课程”中修正。</div>`:''}<div class="table-wrap"><table><thead><tr><th>课程</th><th>星期 / 节次</th><th>周数</th><th>教室 / 教师</th></tr></thead><tbody>${s.courses.map(c=>`<tr><td>${esc(c.name)}</td><td>周${DAYS[c.day-1]} ${c.start}–${c.end}</td><td>${formatWeeks(c.weeks)}</td><td>${esc(c.room)}<br>${esc(c.teacher)}</td></tr>`).join('')}</tbody></table></div>${s.notes.length?`<p class="notice" style="margin-top:12px">${s.notes.map(esc).join('<br>')}</p>`:''}<form id="import-form"><div class="form-grid" style="margin-top:18px">${field('课表名称','name',s.name,'text','required maxlength="80"')}${field('第 1 周周一（可稍后设置）','startDate',s.startDate,'date')}</div><p class="muted">确认后新建课表，已有课表保留。节次时间默认为示例，导入后请到设置中核对。</p><button class="primary" type="submit">确认导入 ${s.courses.length} 条时段</button></form>`);
}
function rowsToCSV(rows){return rows.map(r=>r.map(x=>'"'+String(x??'').replace(/"/g,'""')+'"').join(',')).join('\n');}
async function importFile(file){if(!file)return;if(file.size>20*1024*1024)throw Error('文件不能超过 20 MB');toast('正在本地解析，请稍候…');const ext=file.name.split('.').pop().toLowerCase();let result;
 if(ext==='pdf')result=await readPDF(await file.arrayBuffer());
 else if(ext==='xlsx'){const rows=await readXlsxFile(file);if(rows.some(r=>r.some(x=>x instanceof Date)))throw Error('Excel 将周数转换成了日期，请把周数列设为文本后重填');result={courses:parseCSV(rowsToCSV(rows))};}
 else{let text=new TextDecoder('utf-8',{fatal:false}).decode(await file.arrayBuffer());if(text.includes('\ufffd'))text=new TextDecoder('gb18030').decode(await file.arrayBuffer());
 if(ext==='json'){const raw=JSON.parse(text);result={schedule:raw.format==='keyu-v1'?raw.schedule:raw};}
 else if(ext==='html'||ext==='htm'){const dom=new DOMParser().parseFromString(text,'text/html'),table=[...dom.querySelectorAll('table')].find(t=>t.textContent.includes('课程名称')&&t.textContent.includes('开始节数'));if(!table)throw Error('HTML 需为七列表头的课程数据表，当前教务网页布局尚未适配');result={courses:parseCSV(rowsToCSV([...table.rows].map(r=>[...r.cells].map(c=>c.textContent.trim()))))};}
 else result={courses:parseCSV(text)};}
 if(!(result.courses||result.schedule?.courses)?.length)throw Error('文件中没有课程');preview(result,file.name);
}
function demo(){const s=emptySchedule();s.id=uid();s.name='秋日课表 · 虚构示例';s.startDate='2026-08-31';s.courses=[['高等数学',1,1,2,'明理楼 A201'],['程序设计',2,3,4,'知行楼 B302'],['大学物理',3,1,2,'明理楼 A108'],['大学英语',4,3,4,'博学楼 C206'],['线性代数',5,1,2,'明理楼 A201'],['体育',2,7,8,'东区田径场'],['设计与生活',3,5,6,'创意工坊'],['程序设计实验',5,5,8,'计算机中心']].map((r,i)=>course({name:r[0],day:r[1],start:r[2],end:r[3],room:r[4],weeks:'1-18',teacher:'示例教师',color:COLORS[i%6]}));commit({...state,active:s.id,schedules:[...state.schedules,s]});week=3;view='week';render();toast('已加载虚构示例，不是学校正式课表');}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
 if(b.dataset.view){view=b.dataset.view;render();return;}
 if(b.dataset.course){editCourse(b.dataset.course);return;}
 if(b.dataset.deleteCourse){if(confirm('确定删除这条课程时段？')){saveSchedule({...current(),courses:current().courses.filter(c=>c.id!==b.dataset.deleteCourse)});close();}return;}
 if(b.dataset.removeAdjust){const a={...current().adjustments};delete a[b.dataset.removeAdjust];saveSchedule({...current(),adjustments:a});return;}
 const a=b.dataset.action,s=current();
 if(a==='close')close();if(a==='add')editCourse();if(a==='demo')demo();
 if(a==='prev'||a==='next'||a==='today'){week=clampWeek(a==='today'?weekOf(s,today()):week+(a==='next'?1:-1));render();}
 if(a==='pick'){$('#file-input').accept=b.dataset.accept;$('#file-input').click();}
 if(a==='template')download('课屿-导入模板.csv',exportCSV({courses:[course({name:'示例课程',day:1,start:1,end:2,teacher:'示例教师',room:'教学楼101',weeks:'3-12、15-18'})]}),'text/csv;charset=utf-8');
 if(a==='paste')modal('粘贴 CSV 文本','<form id="paste-form"><label class="field">包含七列表头的 CSV<textarea name="text" rows="10" required placeholder="课程名称,星期,开始节数,结束节数,老师,地点,周数"></textarea></label><button class="primary" type="submit">预览解析结果</button></form>');
 if(a==='export')exportDialog();
 if(a==='json')download('课屿-备份.json',JSON.stringify({format:'keyu-v1',schedule:s},null,2),'application/json');
 if(a==='csv')download('课屿-课程.csv',exportCSV(s),'text/csv;charset=utf-8');
 if(a==='ics')download('课屿-课程.ics',exportICS(s),'text/calendar;charset=utf-8');
 if(a==='adjust')modal('添加停课 / 补课',`<form id="adjust-form">${field('需要调整的实际日期','date',today(),'date','required')}${select('安排','kind',[['off','当天停课'],['copy','使用另一日期原本的课程']],'off')}${field('补课来源日期（停课时留空）','source','','date')}<p class="muted">补课不会自动取消来源日期的课程。如需取消，请另加一条停课。</p><button class="primary" type="submit">保存安排</button></form>`);
 if(a==='delete-schedule'&&confirm(`删除「${s.name}」？建议先导出 JSON 备份。`)){let remaining=state.schedules.filter(x=>x.id!==s.id);if(!remaining.length)remaining=[emptySchedule()];week=1;commit({...state,schedules:remaining,active:remaining[0].id});}
 if(a==='notifications'){if(!s.startDate)throw Error('请先设置第 1 周日期');native.enableReminders();}
 if(a==='native-settings')native.openSettings();if(a==='disable-notifications')native.disableReminders();
 }catch(err){if(!$('#modal').hidden)$('#form-error').textContent=err.message;else toast(err.message);}});
document.addEventListener('submit',e=>{e.preventDefault();const form=e.target,f=Object.fromEntries(new FormData(form)),s=current();try{
 if(form.id==='course-form'){const c=course({...f,id:form.dataset.id}),cs=s.courses.filter(x=>x.id!==c.id);saveSchedule({...s,courses:[...cs,c]});close();const n=conflicts(current()).length;toast(n?`已保存。存在 ${n} 组课程时间冲突，请核对。`:'课程已保存');}
 if(form.id==='settings-form'){saveSchedule({...s,...f,totalWeeks:+f.totalWeeks,reminder:+f.reminder,slots:f.slots.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),notes:f.notes.split(/\r?\n/).filter(x=>x.trim())});week=clampWeek(week);render();toast('设置已保存');}
 if(form.id==='import-form'){const ns=validateSchedule({...pending,name:f.name,startDate:f.startDate});view='week';week=Math.max(1,Math.min(ns.totalWeeks,weekOf(ns,today())));commit({...state,active:ns.id,schedules:[...state.schedules,ns]});pending=null;close();toast('导入成功，请核对节次时间');}
 if(form.id==='paste-form')preview({courses:parseCSV(f.text)},'粘贴的课表');
 if(form.id==='adjust-form'){if(!s.startDate)throw Error('请先设置第一周日期');if(f.kind==='copy'&&!f.source)throw Error('请选择补课来源日期');saveSchedule({...s,adjustments:{...s.adjustments,[f.date]:f.kind==='off'?null:f.source}});close();toast('调休安排已保存');}
 }catch(err){(form.id==='settings-form'?$('#settings-error'):$('#form-error')).textContent=err.message;}});
document.addEventListener('change',async e=>{try{if(e.target.id==='file-input'){const file=e.target.files[0];e.target.value='';await importFile(file);}if(e.target.id==='schedule-switch'){state.active=e.target.value;week=clampWeek(weekOf(current(),today()));persist();render();}if(e.target.name==='theme'){commit({...state,theme:e.target.value});}}catch(err){toast(err.message);}});
document.addEventListener('input',e=>{if(e.target.id==='search'){const q=e.target.value.trim().toLowerCase();$('#course-list').innerHTML=listItems(current().courses.filter(c=>[c.name,c.teacher,c.room].join(' ').toLowerCase().includes(q)));}});
document.addEventListener('keydown',e=>{if($('#modal').hidden)return;if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=[...$('#modal').querySelectorAll('button,input,select,textarea')].filter(x=>!x.disabled),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
globalThis.keyuNativeStatus=()=>{if(view==='settings')render();};
render();if(native)syncNative();
if('serviceWorker' in navigator&&!native&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(()=>toast('离线缓存未完成，首次使用请保持联网'));
